services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=chat'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
  #backend:
  #  build: .
  #  ports:
  #    - '8080:8080'
  #  depends_on:
  #    - 'db'