services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USERNAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    restart: 'unless-stopped'
  #backend:
  #  build: .
  #  ports:
  #    - '8080:8080'
  #  depends_on:
  #    - 'db'